# Scan this file for changes every 30 seconds
#refresh_rate: 30 seconds

appenders:
    # An appender named "stdout" that writes to stdout
    stdout:
        kind: console
        encoder:
            pattern: "{d(%H:%M:%S:%.3f)} {l} {t} - {m}{n}"

    # An appender named "chain_scraper" that writes to a file with a custom pattern encoder
    file_appender:
        kind: file
        path: "log/file_appender.log"
        encoder:
            pattern: "{d(%H:%M:%S:%.3f)} {l} {t} - {m}{n}"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
    level: info
    appenders:
        - stdout
        - file_appender

loggers:
    # Raise the maximum log level for events sent to the "app::backend::db" logger to "info"
#    app::backend::db:
#        level: info

    # Route log events sent to the "chain_scraper" logger/module to the "file_appender" appender,
    # and *not* the normal appenders installed at the root
    actix_web:
        level: debug
        appenders:
            - stdout
            - file_appender
        additive: false

    chain_scraper:
        level: debug
        appenders:
            - stdout
            - file_appender
        additive: false